apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-java-quarkus-rolkepxg
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/tsscui/backend-tests-java-quarkus-rolkepxg:azure-0f9942eb791133bb7919cf71cb3f1be5596a5a26
        name: container-image  
